# Generated by Django 6.0.2 on 2026-02-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0002_district_area_km2_district_census_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='female_population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='male_population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
