# Generated by Django 6.0.2 on 2026-02-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0003_district_female_population_district_male_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualitydata',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='month',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='airqualitydata',
            index=models.Index(fields=['year', 'month'], name='air_airqual_year_0e846c_idx'),
        ),
        migrations.AddIndex(
            model_name='airqualitydata',
            index=models.Index(fields=['station', 'year'], name='air_airqual_station_f5ea96_idx'),
        ),
        migrations.AddIndex(
            model_name='airqualitydata',
            index=models.Index(fields=['station', 'date'], name='air_airqual_station_9bc559_idx'),
        ),
    ]
